app_todo/urls.py
from django.conf.urls import patterns, url
from app_todo import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^new$', views.task_create, name='task_new'),
    url(r'^edit/(?P<id>\d+)$', views.task_update, name='task_edit'),
    url(r'^delete/(?P<id>\d+)$', views.task_delete, name='task_delete'),
    url(r'^task-done/(?P<id>\d+)/$', views.mark_as_done, name='task_done'),
    url(r'^sort-tasks$', views.sort_tasks, name='sort_tasks'),
    url(r'^sort-tasks-overdue$', views.sort_tasks_overdue, name='sort_tasks_overdue'),
    url(r'^filter-tasks$', views.filter_by_date, name='filter_tasks'),
)

todo_list/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import app_todo.views
import app_todo.urls

urlpatterns = patterns('',
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app_todo.urls', namespace='app_todo')),
)

app_todo/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.utils import timezone

# Create your models here.
class Task(models.Model):
  description = models.CharField(max_length=100)
  due_date = models.DateTimeField(verbose_name="Due date")
  date_crea = models.DateTimeField(auto_now_add=True, auto_now=False,
                              verbose_name="Date of creation")
  is_done = models.BooleanField(default=False)

  def __str__(self):
    return self.description

  def overdue(self):
    if self.due_date and self.due_date < datetime.now(timezone.utc):
      return self

app_todo/forms.py
from django import forms
from django.forms import widgets

class DateRangeForm(forms.Form):
    start_date = forms.DateTimeField(widget=forms.DateInput)
    end_date = forms.DateTimeField(widget=forms.DateInput)

app_todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from .forms import DateRangeForm
from .models import Task
from datetime import datetime

# Create your views here.

class TaskForm(ModelForm):
  class Meta:
    model = Task
    fields = ['description', 'due_date']

def home(request, template_name='app_todo/home.html'):
  tasks = Task.objects.all()
  ctx = {}
  ctx['tasks'] = tasks
  return render(request, template_name, ctx)

def task_create(request, template_name='app_todo/task_form.html'):
  form = TaskForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('app_todo:home')
  ctx = {}
  ctx['form'] = form
  return render(request, template_name, ctx)

def task_update(request, id, template_name='app_todo/task_form.html'):
  task = get_object_or_404(Task, id=id)
  form = TaskForm(request.POST or None, instance=task)
  if form.is_valid():
    form.save()
    return redirect('app_todo:home')
  ctx = {}
  ctx['form'] = form
  ctx['task'] = task
  return render(request, template_name, ctx)

def task_delete(request, id, template_name='app_todo/task_confirm_delete.html'):
  task = get_object_or_404(Task, id=id)
  if request.method=='POST':
    task.delete()
    return redirect('app_todo:home')
  ctx = {}
  ctx['task'] = task
  return render(request, template_name, ctx)

def mark_as_done(request, id, template_name='app_todo/home.html'):
  task = get_object_or_404(Task, id=id)
  if request.method == 'POST':
    task.is_done = not task.is_done
    task.save()
    return redirect('app_todo:home')
  ctx = {}
  ctx['task'] = task
  return render(request, template_name, ctx)

def sort_tasks(request, template_name='app_todo/home.html'):
  tasks = Task.objects.order_by('-is_done').all()
  ctx = {}
  ctx['tasks'] = tasks
  return render(request, template_name, ctx)

def sort_tasks_overdue(request, template_name='app_todo/home.html'):
  tasks = Task.objects.order_by('due_date').all()
  ctx = {}
  ctx['tasks'] = tasks
  return render(request, template_name, ctx)

def filter_by_date(request, template_name='app_todo/home.html'):
  form = DateRangeForm(request.POST or None)
  if form.is_valid():
    form.save()
    return Task.objects.filter(date_crea__range=(start_date, end_date))
  ctx = {}
  ctx['form'] = form
  return render(request, template_name, ctx)

app_todo/templates/app_todo/home.html
{% extends "base.html" %}

{% block content %}
<h1>My Tasks</h1>
<ul>
    {% for task in tasks %}
    <li>{{ task.description }}  ( due for {{ task.due_date }} )
         {% if task.overdue %}
          OVERDUE
         {% endif %}
      <form method="post" action="{% url 'app_todo:task_done' task.id %}">
          {% csrf_token %}
          <input type="checkbox" {% if task.is_done%} checked="checked" {% endif %} onclick="this.parentNode.submit();" >
      </form>
    </li>
    <a href="{% url 'app_todo:task_edit' task.id %}">Edit</a>
    <a href="{% url 'app_todo:task_delete' task.id %}">Delete</a>
    {% endfor %}
</ul>

<a href="{% url 'app_todo:task_new' %}">New</a>

<form method="post" action="{% url 'app_todo:sort_tasks' %}">
    {% csrf_token %}
    <input type="submit" value="Sort by done" {% if task.sort_tasks%}{% endif %} onclick="this.parentNode.submit();">
</form>

<form method="post" action="{% url 'app_todo:sort_tasks_overdue' %}">
    {% csrf_token %}
    <input type="submit" value="Sort by date" {% if task.sort_tasks%}{% endif %} onclick="this.parentNode.submit();">
</form>

<form action="{% url 'app_todo:filter_tasks' %}" method="POST">
  {% csrf_token %}
  Select tasks per date:
  start Date
  <input type="date" name={{ start_date }}>
  end Date
  <input type="date" name={{ end_date }}>
  <input  type = "submit" name = "submit" value = "See Results">
</form>


{% endblock %}

app_todo/templates/app_todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ task }}" ?
    <input type="submit" value="Hell yeah!" />
</form>

{% endblock %}

app_todo/templates/app_todo/task_form.html
{% extends "base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>TODO-LIST: {% block title %}Welcome{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" media="all" rel="stylesheet" />
</head>

<body>
<div id="wrapper">

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div><!-- wrapper -->
</body>
</html>